"""Shared helpers for the degradability assessment stage (docs §3, scripts/10*).

Deliberately thin, in the same spirit as `src/essentiality.py`: it **reuses** the ligandability
helpers (`src/ligandability.py`) for the generic machinery — organism config, proteome loading, the
03a ortholog table, DIAMOND, output paths — and the essentiality helpers for the E. coli -> Kp
ortholog transfer. On top of that it adds only what is degradability-specific:

  * `terminal_plddt()` / `init_region_len()` / `exposure()` — the structural half of docs §3.1a/§3.1b.
    The spec's central idea (down-weight a degron motif when the terminus sits in a folded,
    high-pLDDT region) was never implemented by the legacy prototype; this is it. We read the
    AlphaFold models from the **existing** `data/processed/<org>/pockets/pdb/<ACC>.pdb` cache written
    by 06e (B-factor == pLDDT), rather than re-parsing the mmCIFs.
  * corrected degron motif definitions (see the MOTIFS table below for why each legacy regex changed),
    each with the published archetype it must match — asserted by `selftest_motifs()`.
  * `growth_corrected_kdeg()` — pulsed-SILAC half-lives conflate proteolysis with growth dilution.
  * the per-paper Clp-trap weights and the auditable scoring constants used by the 10h merge.

Keying is always by UniProt accession (project convention). Run with the `gradi` conda env.

Why the legacy motif set was replaced rather than tuned
-------------------------------------------------------
The deleted prototype (`git show 8327de3^:scripts/03_annotate_clp_degradability.py`) had three
defects that a weight change cannot fix:

1. **The N-end rule feature was inverted.** Met-aminopeptidase excises the initiator Met only when
   residue 2 has a small side chain (A,C,G,P,S,T,V; Hirel 1989). When residue 2 is L/F/Y/W the iMet
   is *retained*, and Met is a *stabilizing* N-terminal residue in E. coli — so `pos2 in LFYW`
   selects precisely the proteins that cannot expose an N-degron by iMet cleavage. It fired on 684
   Kp proteins at +0.25 each and single-handedly produced 680 of the 698 "medium" calls. Measured
   enrichment for fast turnover against the real Nagar 2021 classes: 1.30x, i.e. noise. Bacterial
   N-degrons are physiologically generated by endoproteolysis or by Aat-mediated Leu/Phe transfer
   (Erbse 2006, Ninnis 2009), which cannot be predicted from the primary sequence. We therefore emit
   `nend_primary_destabilizing` AND `nend_imet_cleaved` as provenance columns and weight both 0.
2. **The CM1 regex did not match its own archetype.** `[YAFWLIVM]?[ALV]A[ALV]A$` fails on the ssrA
   tag `AANDENYALAA`. Its 5 proteome-wide "hits" (AAALA, KLAVA, TAAAA, PLALA, RLALA) are unrelated
   to ssrA. Replaced, and `selftest_motifs()` now asserts the archetype match.
3. **CM2/MuA carries no signal** in the only labelled data we have (0 fast-degraders among 28 hits).
   Kept as a column for transparency, weight 0.

Consequently the weighting shifts decisively away from sequence motifs and onto terminal structural
exposure (the one dense, correctly-signed, full-coverage feature) plus experimental evidence.
"""

from __future__ import annotations

import math
import re
import sys
from pathlib import Path

import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from src import essentiality as E  # noqa: E402
from src import ligandability as L  # noqa: E402

# Re-export so the 10* scripts can reach everything through `from src import degradability as D`.
ORGANISMS = L.ORGANISMS
ORG_DISPLAY = E.ORG_DISPLAY
acc_from_header = L.acc_from_header
load_accessions = L.load_accessions
load_diamond_hits = L.load_diamond_hits
load_genes = L.load_genes
load_orthologs = L.load_orthologs
ortholog_map = L.ortholog_map
orthologs_long_tsv = L.orthologs_long_tsv
processed_dir = L.processed_dir
proteome_fasta = L.proteome_fasta
proteome_tsv = L.proteome_tsv
results_dir = L.results_dir
run_diamond_blastp = L.run_diamond_blastp
transfer_ecoli_to_kp = E.transfer_ecoli_to_kp

# Species keys as they appear in the 03a `{kp,ec}_orthologs_long.tsv` `species` column. The panel
# already covers every organism the §3.3b trap papers were done in, so docs §3.3a (an OrthoDB
# cross-bacterial expansion) needs no separate fetch — see docs/degradability_log.md.
SPECIES_ECOLI = "Ecoli_K12_MG1655"
SPECIES_KP = "Kpneumoniae_HS11286"
XBAC_SPECIES = {
    "caulobacter": "Caulobacter_vibrioides",
    "mtuberculosis": "Mtuberculosis_H37Rv",
    "saureus": "Saureus_NCTC8325",
    "bsubtilis": "Bsubtilis_168",
}


# --------------------------------------------------------------------------- paths
def degradability_raw_dir(organism: str, *parts: str) -> Path:
    d = REPO_ROOT / "data" / "raw" / organism / "degradability"
    for p in parts:
        d = d / p
    d.mkdir(parents=True, exist_ok=True)
    return d


def xbac_raw_dir(*parts: str) -> Path:
    """Cross-/multi-species degradability inputs (the non-E.-coli Clp-trap papers)."""
    d = REPO_ROOT / "data" / "raw" / "other" / "degradability"
    for p in parts:
        d = d / p
    d.mkdir(parents=True, exist_ok=True)
    return d


def degradability_processed_dir(organism: str, *parts: str) -> Path:
    return L.processed_dir(organism, "degradability", *parts)


def xbac_processed_dir(*parts: str) -> Path:
    d = REPO_ROOT / "data" / "processed" / "other" / "degradability"
    for p in parts:
        d = d / p
    d.mkdir(parents=True, exist_ok=True)
    return d


def legacy_clp_dir(*parts: str) -> Path:
    """The pre-reorganization hand-curated Clp stand-in tables (45-row Flynn, 35-row Nagar).

    Kept only as a *fallback* when the real published tables cannot be fetched, and always
    provenance-flagged as `curated_standin` so it is never mistaken for the primary source.
    """
    d = REPO_ROOT / "data" / "raw" / "legacy" / "clp_substrates"
    for p in parts:
        d = d / p
    return d


def af_pdb_path(organism: str, accession: str) -> Path:
    """AlphaFold model as pdb with pLDDT in the B-factor, from the 06e conversion cache.

    5,727 K. pneumoniae / 4,371 E. coli models are already converted there, so the structural
    degron features need no download and no mmCIF re-parse.
    """
    return L.processed_dir(organism, "pockets", "pdb") / f"{accession}.pdb"


# --------------------------------------------------------------------------- structural exposure
# AlphaFold's conventional confidence break: pLDDT < 70 is "low confidence", and in monomeric
# predictions such regions are the standard proxy for intrinsic disorder. It is also the threshold
# the disorder filter in docs §2.4 uses, so degradability and ligandability stay commensurable.
PLDDT_DISORDER_CUT = 70.0
# Logistic width, in pLDDT units, of the ordered->disordered transition. 8 puts exposure at ~0.08
# for a well-folded terminus (pLDDT 90) and ~0.92 for a clearly disordered one (pLDDT 50), while
# staying smooth across the observed p10-p90 band (~54-97).
EXPOSURE_WIDTH = 8.0
# ClpXP/ClpAP need an unstructured initiation region to thread into the pore before unfolding can
# begin; the Sauer-lab estimate is roughly 10-30 residues. We report the measured length and use 15
# as the "engageable" floor for the bimodal degrader flag.
MIN_INIT_REGION = 15


def residue_plddt(pdb_path: Path) -> dict[int, float]:
    """Mean B-factor (== pLDDT) per residue number, parsed straight from the pdb.

    Same implementation as `residue_plddt` in scripts/06e_pockets.py, promoted here so both the
    pocket and the degron tracks share one parser (numpy-free so this module stays import-light).
    """
    acc: dict[int, list[float]] = {}
    with open(pdb_path) as fh:
        for line in fh:
            if line.startswith(("ATOM", "HETATM")):
                try:
                    resnum = int(line[22:26])
                    b = float(line[60:66])
                except ValueError:
                    continue
                acc.setdefault(resnum, []).append(b)
    return {r: sum(v) / len(v) for r, v in acc.items() if v}


def plddt_series(organism: str, accession: str) -> list[float]:
    """Per-residue pLDDT in residue order, or [] when no AlphaFold model is cached."""
    p = af_pdb_path(organism, accession)
    if not p.exists():
        return []
    per_res = residue_plddt(p)
    return [per_res[r] for r in sorted(per_res)]


def terminal_plddt(plddt: list[float], n: int = 10, terminus: str = "c") -> float | None:
    """Mean pLDDT over the last (`terminus="c"`) or first (`"n"`) `n` residues.

    For the N-terminus we start at residue 2, since residue 1 is the initiator Met (frequently
    excised) and its pLDDT is systematically low in AlphaFold models regardless of local order.
    """
    if not plddt:
        return None
    seg = plddt[-n:] if terminus == "c" else plddt[1:1 + n]
    if not seg:
        return None
    return round(sum(seg) / len(seg), 2)


def init_region_len(plddt: list[float], terminus: str = "c",
                    cut: float = PLDDT_DISORDER_CUT) -> int | None:
    """Length of the contiguous low-pLDDT run at a terminus — the candidate pore-initiation region.

    This is the mechanistically meaningful quantity (an unstructured segment long enough to thread),
    not the mean pLDDT: a 25-residue disordered tail on an otherwise rigid protein barely moves the
    terminal mean but is exactly what ClpXP needs.
    """
    if not plddt:
        return None
    seq = list(reversed(plddt)) if terminus == "c" else plddt[1:]
    k = 0
    for v in seq:
        if v < cut:
            k += 1
        else:
            break
    return k


def exposure(plddt: float | None, midpoint: float = PLDDT_DISORDER_CUT,
             width: float = EXPOSURE_WIDTH) -> float | None:
    """Map a terminal pLDDT to a [0,1] exposure/flexibility score (logistic, high pLDDT -> 0).

    None propagates as None so 10h can renormalise the weight away rather than scoring a protein
    with no AlphaFold model as if its terminus were buried.
    """
    if plddt is None or pd.isna(plddt):
        return None
    return round(1.0 / (1.0 + math.exp((float(plddt) - midpoint) / width)), 4)


# --------------------------------------------------------- disorder architecture (docs §3.1, 10d)
# Terminal windows the spec asks for. 10b used (10, 20); 30 matters specifically because Won 2024's
# top feature is the mean disorder of the N-terminal ~30 residues, so parity with that result needs
# a 30-residue window.
TERM_WINDOWS_SPEC = (15, 30, 50)
# Measured ClpXP initiation-region thresholds, in residues:
#   ~5  closed axial channel, 2 pore-1 loops engaged      (Saunders 2020 PNAS)
#   ~20 open axial channel, 5 pore-1 loops engaged        (Saunders 2020; Fei 2020 eLife)
#   ~37 pore-to-ClpP-active-site reach                    (Kenniston 2005 PNAS)
# Longer tails also shift the balance from futile release toward committed degradation.
INIT_THRESHOLDS = (5, 20, 37)
INIT_BUCKETS = ("none", "recognition", "engagement", "reach")
# A stricter disorder call than the pLDDT<70 confidence break, for the "clearly disordered" variant.
PLDDT_DISORDER_CUT_STRICT = 50.0
# An internal low-pLDDT stretch this long is a candidate internal degron. Degrons need not be
# terminal: internally placed ssrA tags are degraded by ClpAP/ClpXP (Hoskins 2002), and E. coli FtsZ
# carries an internal ClpXP site in its disordered linker at residues 349-358 (Camberg 2014).
MIN_INTERNAL_RUN = 10


def init_bucket(length: int | None) -> str | None:
    """Bucket an initiation-region length against the measured ClpXP thresholds."""
    if length is None or pd.isna(length):
        return None
    lo, mid, hi = INIT_THRESHOLDS
    n = int(length)
    if n >= hi:
        return "reach"
    if n >= mid:
        return "engagement"
    if n >= lo:
        return "recognition"
    return "none"


def internal_disorder_runs(plddt: list[float],
                           cut: float = PLDDT_DISORDER_CUT) -> dict[str, float | int | None]:
    """Low-pLDDT runs that touch NEITHER terminus — the internal-degron / linker case.

    Terminal runs are already `init_region_len()`; excluding them here keeps the two features
    independent, so a long disordered tail cannot masquerade as an internal linker.

    Returns max run length, run count, the fraction of residues in internal runs, and the 1-based
    start/end of the longest run (so a hit can be checked against a published site — e.g. FtsZ
    349-358).
    """
    out: dict[str, float | int | None] = {
        "internal_disorder_max_run": None, "internal_disorder_n_segments": None,
        "internal_disorder_frac": None, "internal_disorder_start": None,
        "internal_disorder_end": None,
    }
    if not plddt:
        return out
    n = len(plddt)
    runs: list[tuple[int, int]] = []   # (start_idx, end_idx) inclusive, 0-based
    i = 0
    while i < n:
        if plddt[i] < cut:
            j = i
            while j + 1 < n and plddt[j + 1] < cut:
                j += 1
            runs.append((i, j))
            i = j + 1
        else:
            i += 1
    internal = [(a, b) for a, b in runs if a > 0 and b < n - 1]
    out["internal_disorder_n_segments"] = len(internal)
    out["internal_disorder_frac"] = round(sum(b - a + 1 for a, b in internal) / n, 4)
    if internal:
        a, b = max(internal, key=lambda r: r[1] - r[0])
        out["internal_disorder_max_run"] = b - a + 1
        out["internal_disorder_start"] = a + 1      # 1-based, to compare against literature sites
        out["internal_disorder_end"] = b + 1
    else:
        out["internal_disorder_max_run"] = 0
    return out


def global_disorder_frac(plddt: list[float], cut: float = PLDDT_DISORDER_CUT) -> float | None:
    """Fraction of residues below `cut`. At cut=70 this is the same definition as the ligandability
    `disorder_frac` (06g: af_frac_low_plddt + af_frac_very_low_plddt), deliberately — the two axes
    must stay commensurable, since disorder is a *penalty* there and a *positive* here."""
    if not plddt:
        return None
    return round(sum(1 for v in plddt if v < cut) / len(plddt), 4)


# --------------------------------------------------------------------------- MobiDB
# One bulk TSV per proteome, long format: acc / feature / start..end / content_fraction /
# content_count / length. Supplies 8 independent disorder predictors plus a consensus, an
# AlphaFold-derived disorder track, Pfam/Gene3D/merged domain boundaries, LIP (linear interacting
# peptide) regions and low-complexity — at 100% of both proteomes.
#
# Why it matters beyond convenience: pLDDT-derived disorder has a known failure mode — an obligate
# complex subunit is ordered in situ but predicted disordered in isolation — so an independent
# sequence-side opinion is the guard against reading assembly context as intrinsic disorder.
MOBIDB_PREDICTORS = ("dis465", "disHL", "glo", "th_50", "espX", "iups", "espN", "iupl")


def mobidb_tsv(organism: str) -> Path | None:
    d = degradability_raw_dir(organism, "mobidb")
    files = sorted(d.glob("*_mobidb_*.tsv"))
    return files[0] if files else None


def load_mobidb(organism: str) -> pd.DataFrame:
    """Pivot the MobiDB long export to one row per accession.

    Columns: uniprot_accession, seq_len_mobidb, mobidb_dis_<predictor> (8), mobidb_disorder_priority
    (the consensus), mobidb_disorder_alphafold, mobidb_plddt_alphafold, mobidb_lip_frac,
    mobidb_low_complexity_frac, mobidb_n_domains_{pfam,gene3d,merge}, mobidb_predictor_agreement
    (how many of the 8 predictors call >10% disorder — a spread measure, not a mean).

    Returns an empty frame when the bulk file is absent, so 10d degrades to pLDDT-only rather than
    failing.
    """
    f = mobidb_tsv(organism)
    if f is None:
        return pd.DataFrame(columns=["uniprot_accession"])
    raw = pd.read_csv(f, sep="\t", usecols=["acc", "feature", "start..end", "content_fraction",
                                            "content_count", "length"])
    raw["acc"] = raw["acc"].astype(str).str.strip()

    def _frac(feature: str, name: str) -> pd.DataFrame:
        sub = raw[raw["feature"] == feature][["acc", "content_fraction"]]
        return sub.drop_duplicates("acc").rename(columns={"content_fraction": name})

    out = raw[["acc", "length"]].drop_duplicates("acc").rename(columns={"length": "seq_len_mobidb"})
    for p in MOBIDB_PREDICTORS:
        out = out.merge(_frac(f"prediction-disorder-{p}", f"mobidb_dis_{p}"), on="acc", how="left")
    for feat, name in (("prediction-disorder-priority", "mobidb_disorder_priority"),
                       ("prediction-disorder-alphafold", "mobidb_disorder_alphafold"),
                       ("prediction-plddt-alphafold", "mobidb_plddt_alphafold"),
                       ("prediction-lip-priority", "mobidb_lip_frac"),
                       ("prediction-low_complexity-seg", "mobidb_low_complexity_frac")):
        out = out.merge(_frac(feat, name), on="acc", how="left")

    # Domain counts. MobiDB emits ONE row per accession per source and packs every domain into a
    # comma-separated `start..end` ("23..143,177..229,235..295,299..452" = 4 domains), so counting
    # rows gives 1 for everything. Count the ranges instead.
    for feat, name in (("homology-domain-pfam", "mobidb_n_domains_pfam"),
                       ("homology-domain-gene3d", "mobidb_n_domains_gene3d"),
                       ("homology-domain-merge", "mobidb_n_domains_merge")):
        sub = raw[raw["feature"] == feat][["acc", "start..end"]].drop_duplicates("acc").copy()
        sub[name] = sub["start..end"].astype(str).str.count(",") + 1
        out = out.merge(sub[["acc", name]], on="acc", how="left")
    for c in ("mobidb_n_domains_pfam", "mobidb_n_domains_gene3d", "mobidb_n_domains_merge"):
        out[c] = out[c].fillna(0).astype(int)

    # MobiDB's bulk export lists only the regions a predictor FOUND. A protein the predictor judged
    # fully ordered simply has no row, so a left-join NaN means "zero disorder", not "not computed"
    # — verified: accessions with no `priority` row still carry dis465 fractions of 0.10-0.26, i.e.
    # the consensus declined to call a region rather than the predictor not having run. Treating
    # those as missing understates coverage and silently drops them from any downstream mean.
    region_fracs = ([f"mobidb_dis_{p}" for p in MOBIDB_PREDICTORS]
                    + ["mobidb_disorder_priority", "mobidb_lip_frac",
                       "mobidb_low_complexity_frac"])
    for c in region_fracs:
        if c in out.columns:
            out[c] = out[c].fillna(0.0)
    # `mobidb_plddt_alphafold` is a confidence value, not a region fraction, and
    # `mobidb_disorder_alphafold` only exists where a model does — both stay NaN when absent.

    pred_cols = [f"mobidb_dis_{p}" for p in MOBIDB_PREDICTORS]
    out["mobidb_predictor_agreement"] = (out[pred_cols] > 0.10).sum(axis=1)
    return out.rename(columns={"acc": "uniprot_accession"}).reset_index(drop=True)


# --------------------------------------------------------------------------- feature scoring
AUROC_BOOTSTRAP = 2000
AUROC_SEED = 0


def _auroc(v, y) -> float:
    """AUROC from the Mann-Whitney U statistic (no threshold, invariant to monotone rescaling)."""
    from scipy import stats
    n_pos = int(y.sum())
    n_neg = int(len(y) - n_pos)
    ranks = stats.rankdata(v)
    return float((ranks[y].sum() - n_pos * (n_pos + 1) / 2) / (n_pos * n_neg))


def disorder_auroc(values, labels, n_boot: int = AUROC_BOOTSTRAP) -> dict[str, float | int | None]:
    """Score one continuous feature against a binary label: AUROC + bootstrap CI + Spearman + n.

    AUROC answers the question that matters here — "does this feature rank fast-turnover proteins
    above stable ones" — without needing a threshold. 0.5 is the null.

    **The CI is not optional.** The labelled positive class is ~60-75 proteins, so the 95% interval on
    an AUROC is roughly +/-0.07. Reporting a bare ranking at that sample size invites reading a
    0.03 gap between two features as a real difference when it is noise. Every consumer of this
    function must plot or print `auroc_lo`/`auroc_hi` alongside the point estimate.

    Returns {auroc, auroc_lo, auroc_hi, spearman, n, n_pos}; auroc is None when either class is empty.
    """
    import numpy as np
    from scipy import stats

    v = pd.Series(values).astype(float)
    y = pd.Series(labels).astype(bool)
    ok = v.notna() & y.notna()
    v, y = v[ok].to_numpy(), y[ok].to_numpy()
    n_pos, n_neg = int(y.sum()), int((~y).sum())
    if n_pos == 0 or n_neg == 0:
        return {"auroc": None, "auroc_lo": None, "auroc_hi": None, "spearman": None,
                "n": int(len(v)), "n_pos": n_pos}

    point = _auroc(v, y)
    rho = float(stats.spearmanr(v, y.astype(int)).statistic) if len(v) > 2 else float("nan")

    lo = hi = None
    if n_boot:
        rng = np.random.default_rng(AUROC_SEED)
        pos_idx = np.flatnonzero(y)
        neg_idx = np.flatnonzero(~y)
        boots = np.empty(n_boot)
        for b in range(n_boot):
            # Stratified resample: keep the class balance fixed so the CI reflects uncertainty in the
            # ranking, not in the prevalence.
            idx = np.concatenate([rng.choice(pos_idx, n_pos, replace=True),
                                  rng.choice(neg_idx, n_neg, replace=True)])
            boots[b] = _auroc(v[idx], y[idx])
        lo, hi = (round(float(x), 4) for x in np.percentile(boots, [2.5, 97.5]))

    return {"auroc": round(point, 4), "auroc_lo": lo, "auroc_hi": hi,
            "spearman": round(rho, 4), "n": int(len(v)), "n_pos": n_pos}


# --------------------------------------------------------------------------- degron motifs
# Residue 2 identities for which Met-aminopeptidase excises the initiator Met (Hirel 1989). Used
# only to make the legacy sign error auditable — neither this nor its complement is scored.
MAP_CLEAVED = set("ACGPSTV")
# Primary destabilizing residues of the bacterial N-end rule (ClpS -> ClpAP). Scored 0: exposing one
# of these requires prior endoproteolysis or Aat transfer, which sequence alone cannot predict.
NEND_DESTABILIZING = set("LFYW")

# CM1, the ssrA/-LAA family (Flynn 2003). The archetypal ClpXP degron is the ssrA tag's C-terminus
# `...AANDENYALAA`. Two nested definitions are emitted so the reader can pick the operating point:
# `broad` (terminal -AA) and `strict` (terminal -AA preceded by a hydrophobic, i.e. the -LAA core).
CM1_BROAD_RX = re.compile(r"AA$")
CM1_STRICT_RX = re.compile(r"[LVIAFMY]AA$")
# CM2, the MuA family (Flynn 2003 archetype `-RRKKAI`): a basic patch followed by small aliphatics.
# Retained for transparency but WEIGHT 0 — it shows no enrichment in the only labelled set we have.
CM2_RX = re.compile(r"[RK]{2,}[A-Z]{0,2}[AVILMG]{1,3}$")
# NM2 (Flynn 2003): initiator Met, basic residue, then two hydrophobics.
NM2_RX = re.compile(r"^M[KR][ILVF][ILVFY]")

# NM1 and NM3 (Flynn 2003), implemented 2026-08-06 from the paper itself — see the block below for
# why the previous stand-ins were wrong and what changed.
#
# Flynn's residue classes for the N-motifs. `phi` = "hydrophobic side chain" in the paper.
NM_HYDROPHOBIC = "AILMFWVY"
NM_POLAR = "STNQCYHKRDE"      # polar incl. charged, which is how the paper's "polar" reads
NM_BASIC = "KRH"
# NM1 strict consensus: T-X-K-[ILV], "located from 1 to 4 residues from the N terminus". That phrase
# means 1-4 residues sit BEFORE the motif, not that T is at position <=4 — verified against Flynn's own
# two named archetypes: Dps `MSTAKLV` (T at position 3, so 2 residues before) and sigma-S/RpoS
# `MSQNTLKV` (T at position 5, so 4 residues before). An upper bound of 4 admits both; a "T at
# position <=4" reading would reject RpoS.
NM1_RX = re.compile(r"^.{1,4}T.K[ILV]")
# NM3 consensus: phi-X-polar-X-polar-X-basic-polar, near the N terminus. Archetypes Crl `MTLPSGHPKS`
# (matches from position 3) and DksA `MQEGQNRK` (from position 1), hence the 0-3 residue lead-in.
NM3_RX = re.compile(
    rf"^.{{0,3}}[{NM_HYDROPHOBIC}].[{NM_POLAR}].[{NM_POLAR}].[{NM_BASIC}][{NM_POLAR}]"
)

# Flynn's NM1 and NM3 ARE now implemented (above), 2026-08-06. History: the legacy `^M?[AILVMFW]{2,}` fired on
# 30.7% of the Kp proteome, and Nagar 2021's own NM1/NM3 flags (which are whole-sequence windowed
# scans, not terminal motifs) fire on 50%/74% of E. coli with no enrichment for fast turnover. A
# feature at that prevalence is a hydrophobicity/length prior, not a degron.
#
# RESOLVED (2026-08-06) — the justification above did not survive reading the paper. Flynn 2003 is now
# on disk (`data/raw/other/degradability/literature/PIIS1097276503000601.pdf`) and `^M?[AILVMFW]{2,}` is NOT NM1. The actual
# published consensuses are much more specific:
#
#   N-M1  strict:  T(1) - X(2) - K(3) - [ILV](4),  located 1-4 residues from the N terminus
#         looser:  polar - T/hydrophobic - hydrophobic - basic - hydrophobic
#         18 of the 60 trapped proteins (sigma-O, Dps + 16 others)
#   N-M3           hydrophobic-X-polar-X-polar-X-basic-polar
#         10 of the 60 (Crl, DksA + 8)
#   N-M2           12 of the 60 (DadA, IscS, OmpA + 9)
#
# A four-residue anchored pattern cannot fire on 30% of a proteome, so the prevalence argument was
# against the wrong regex. MEASURED after implementing the real consensuses, over E. coli (n=4,403):
#
#   NM1  (T-X-K-[ILV], 1-4 in)            22 / 4,403 =  0.50%   <- 55x more specific than the legacy
#   NM3  (phi-X-pol-X-pol-X-bas-pol)     196 / 4,403 =  4.45%
#   legacy `^M?[AILVMFW]{2,}`          1,221 / 4,403 = 27.73%   <- what was actually rejected
#
# So the exclusion was justified for the legacy pattern and NOT justified for Flynn's. NM1 in
# particular is specific enough to be a real feature. Both are WEIGHTED 0 until measured against
# labels — `10e` does that against the Conlon/Jacques activated-ClpP data, which is the first time any
# of these motifs will be tested against the bar the project actually gates on. Flynn also supplies a ready-made positive
# control set of validated C-terminal peptides (ssrA AANDENYALAA, YdaM KNDGRNRVLAA, Crl DFRDEPVKLTA,
# LldD ALAPMAKGNAA, MuA ILEQNRRKKAI, YbaQ ARREERAKKVA, RibB AYRQAHERKAS, Gcp RWPLAELPAA, and Dps
# FLWFIESNIE as a negative for the -AA rule).
#
# NOT a blocker for the axis: these are Regime A (unfoldase) recognition signals, i.e. the SELECTION
# bar. Partnerless activated ClpP — the handle Gr-ADI actually uses — has no sequence degron at all.
# See docs/degradability_datasets.md §3.1.

MOTIFS: dict[str, dict] = {
    "cterm_cm1_broad": {
        "rx": CM1_BROAD_RX, "terminus": "c", "archetype": "AANDENYALAA",
        "desc": "C-terminal -AA (ssrA/CM1 family, permissive)",
    },
    "cterm_cm1_strict": {
        "rx": CM1_STRICT_RX, "terminus": "c", "archetype": "AANDENYALAA",
        "desc": "C-terminal hydrophobic-AA (ssrA/CM1 core, e.g. -LAA)",
    },
    "cterm_cm2": {
        "rx": CM2_RX, "terminus": "c", "archetype": "GSGMSRRKKAI",
        "desc": "C-terminal basic+aliphatic (MuA/CM2 family) — scored 0, no measured signal",
    },
    "nterm_nm2": {
        "rx": NM2_RX, "terminus": "n", "archetype": "MKIIQ",
        "desc": "N-terminal M-[KR]-hydrophobic-hydrophobic (Flynn NM2)",
    },
    # Archetypes are the real N-termini of Flynn's own named proteins, read out of this repo's E. coli
    # proteome rather than transcribed from the paper — the same discipline that caught the CM1 bug.
    "nterm_nm1": {
        "rx": NM1_RX, "terminus": "n", "archetype": "MSTAKLVKSKAT",   # Dps, P0ABT2
        "archetype2": "MSQNTLKVHDLNE",                                # sigma-S / RpoS, P13445
        "desc": "N-terminal T-X-K-[ILV] 1-4 residues in (Flynn NM1, strict consensus)",
    },
    "nterm_nm3": {
        "rx": NM3_RX, "terminus": "n", "archetype": "MTLPSGHPKSRLI",  # Crl, P24251
        "archetype2": "MQEGQNRKTSSLS",                                # DksA, P0ABS1
        "desc": "N-terminal phi-X-polar-X-polar-X-basic-polar (Flynn NM3)",
    },
}

# Motif weights, set from the measured enrichment for fast turnover against the Nagar 2021 classes
# (1,148 labelled E. coli proteins, baseline P(fast)=0.063). 10b recomputes and prints this table on
# every run; the rule is that a motif with an odds ratio near 1 is weighted 0, not down-weighted.
#
#   feature                     proteome hit rate   labelled hits   odds ratio   -> weight
#   cterm_cm1_strict                       0.25%                4        15.24      1.00
#   cterm_cm1_broad                        0.95%               14         3.02      0.40
#   nterm_nm2 (Flynn NM2)                  2.36%               26         0.87      0.00
#   cterm_cm2 (MuA/CM2)                    2.61%               28         0.25      0.00
#   nend_primary_destabilizing            10.33%               98         1.44      0.00
#   nend_imet_cleaved                     40.72%              543         1.92      0.00
#
# Notes on the zeros:
#  * NM2 shows no enrichment (OR 0.87). n=26 is underpowered, so this is "no evidence of an effect"
#    rather than "evidence of no effect" — but weighting an unsupported motif is how the legacy axis
#    ended up reporting one inverted boolean as a degradability score.
#  * CM2 is anti-correlated (OR 0.25, zero fast-degraders among its 28 labelled hits).
#  * `nend_imet_cleaved` is the only N-terminal feature with any signal (OR 1.92), and it is
#    mechanistically sensible — Met-aminopeptidase cleavage is the prerequisite for exposing an
#    N-degron at all. But it fires on 41% of the proteome, so it is a prior, not a motif. Carried as
#    an annotation.
# Consequence, stated plainly: sequence degron motifs cannot carry this axis. Only ~1% of either
# proteome carries a weighted motif, so `degron_score` is driven by terminal structural exposure.
MOTIF_WEIGHTS: dict[str, float] = {
    "cterm_cm1_strict": 1.00,
    "cterm_cm1_broad": 0.40,
    "cterm_cm2": 0.00,
    "nterm_nm2": 0.00,
    # Implemented 2026-08-06 from Flynn's real consensus; weight 0 until 10e measures them
    # against the activator labels. Prevalence is now known (NM1 0.50%, NM3 4.45% of E. coli),
    # which is the prerequisite for a weight, not a substitute for one.
    "nterm_nm1": 0.00,
    "nterm_nm3": 0.00,
    "nend_primary_destabilizing": 0.00,
}


def match_motif(name: str, sequence: str) -> bool:
    """True if `sequence` carries motif `name`. C-terminal motifs are anchored at the C-terminus."""
    spec = MOTIFS[name]
    return bool(spec["rx"].search(sequence.upper()))


def selftest_motifs() -> None:
    """Assert every motif matches the published archetype it claims to encode.

    This is the five-line test whose absence let a CM1 regex that cannot match the ssrA tag ship to
    the browser. Called at the top of 10b so the pipeline cannot run with a broken motif.
    """
    for name, spec in MOTIFS.items():
        for key in ("archetype", "archetype2"):
            arch = spec.get(key)
            if not arch:
                continue
            assert match_motif(name, arch), (
                f"motif {name} fails its {key} {arch!r} — pattern {spec['rx'].pattern!r}"
            )
    # Negative controls: the ssrA tag is not basic-aliphatic, and MuA does not end in -AA.
    assert not match_motif("cterm_cm2", "AANDENYALAA")
    assert not match_motif("cterm_cm1_strict", "GSGMSRRKKAI")
    # N-motif cross-controls: Flynn assigns these to N-M1 and N-M3 respectively, so each must NOT
    # match the other's pattern, or the two features are not separating what they claim to.
    assert not match_motif("nterm_nm3", MOTIFS["nterm_nm1"]["archetype"]), "Dps should not hit NM3"
    assert not match_motif("nterm_nm1", MOTIFS["nterm_nm3"]["archetype"]), "Crl should not hit NM1"
    # And Flynn's N-M2 proteins (DadA, OmpA) belong to neither.
    for nm2_seq in ("MRVVILGSGVVGV", "MKKTAIAIAVALA"):
        assert not match_motif("nterm_nm1", nm2_seq)
        assert not match_motif("nterm_nm3", nm2_seq)


# --------------------------------------------------------------------------- half-life handling
# Nagar 2021 pulsed-SILAC growth condition. Half-lives from a growing culture conflate proteolysis
# with dilution by division, and for this axis only the proteolytic part is evidence: a 34-minute
# apparent half-life in a ~40-minute doubling culture corresponds to a *proteolytic* half-life of
# ~230 minutes. Verified against the paper in docs/degradability_references.md.
NAGAR_DOUBLING_MIN = 40.0
# Nagar's `label` / `Stability` classes, resolved by measuring the median half-life of each class
# (label 1 median 34 min; label 0 median 200 min; label 2 median 411 min with 241 infinite).
NAGAR_LABELS: dict[int, str] = {1: "fast", 0: "intermediate", 2: "stable"}


def nagar_dir() -> Path:
    return degradability_raw_dir("ecoli", "nagar2021_halflife")


def load_nagar() -> pd.DataFrame:
    """Nagar 2021 per-protein turnover, keyed by UniProt accession (E. coli K-12, native evidence).

    Reads `sd002` (1,149 proteins with the paper's own `label` + `half_life`) and enriches it with
    the `sd003` `Stability` class where present. Both sheets key on `Protein IDs`, which already
    holds UniProt accessions — no gene-symbol bridge, so this lands on the anchor proteome directly.

    Columns: uniprot_accession, halflife_min, halflife_class, kdeg_growth_corrected,
             halflife_proteolytic_min, nagar_label.

    Returns an empty frame (not an error) when the fetch has not run, so 10b/10c degrade gracefully.
    """
    cols = ["uniprot_accession", "halflife_min", "halflife_class",
            "kdeg_growth_corrected", "halflife_proteolytic_min", "nagar_label"]
    files = sorted(nagar_dir().glob("*sd002*.xlsx"))
    if not files:
        return pd.DataFrame(columns=cols)
    raw = pd.read_excel(files[0], usecols=["Protein IDs", "label", "half_life"])
    raw = raw.rename(columns={"Protein IDs": "uniprot_accession", "label": "nagar_label",
                              "half_life": "halflife_min"})
    # `Protein IDs` can carry a MaxQuant multi-protein group (`P0A9Q7;P12345`); the first id is the
    # leading/representative protein for the group.
    raw["uniprot_accession"] = (raw["uniprot_accession"].astype(str).str.split(";").str[0].str.strip())
    raw["halflife_min"] = pd.to_numeric(raw["halflife_min"], errors="coerce")
    raw["halflife_class"] = raw["nagar_label"].map(NAGAR_LABELS).fillna("unknown")
    raw["kdeg_growth_corrected"] = raw["halflife_min"].map(growth_corrected_kdeg)
    raw["halflife_proteolytic_min"] = raw["halflife_min"].map(proteolytic_half_life)
    out = raw.drop_duplicates("uniprot_accession")[cols].reset_index(drop=True)
    return out


def growth_corrected_kdeg(t_half_min: float | None,
                          doubling_min: float = NAGAR_DOUBLING_MIN) -> float | None:
    """Proteolytic degradation rate constant (min^-1) from an apparent half-life.

    k_deg = ln2/t_half - mu, with mu = ln2/doubling_min. Clamped at 0: an apparent half-life at or
    above the doubling time means dilution explains the whole signal, i.e. no evidence of
    proteolysis. Returns None for missing/non-positive/infinite input.
    """
    if t_half_min is None or pd.isna(t_half_min):
        return None
    try:
        t = float(t_half_min)
    except (TypeError, ValueError):
        return None
    if t <= 0 or math.isinf(t):
        return None
    mu = math.log(2.0) / float(doubling_min)
    return round(max(0.0, math.log(2.0) / t - mu), 6)


def proteolytic_half_life(t_half_min: float | None,
                          doubling_min: float = NAGAR_DOUBLING_MIN) -> float | None:
    """Growth-corrected half-life in minutes (None when dilution explains the whole decay)."""
    k = growth_corrected_kdeg(t_half_min, doubling_min)
    if not k:
        return None
    return round(math.log(2.0) / k, 1)


# --------------------------------------------------------------------------- evidence weights
# Per-paper weight for pooled Clp-substrate evidence (docs §3.3b + the spec's per-paper-weight
# suggestion). A substrate *trap* is direct physical evidence of engagement; a knockdown/interaction
# screen is weaker inference. `protease` is load-bearing: neither K. pneumoniae HS11286 nor E. coli
# K-12 encodes ClpC, so ClpC/ClpC1-only evidence describes a machine the anchor does not have and is
# capped by CLPC_ONLY_CAP rather than counted as full-strength Clp evidence.
TRAP_PAPERS: dict[str, dict] = {
    "flynn2003": {"species": "ecoli", "protease": "clpxp", "weight": 1.00,
                  "kind": "trap", "citation": "Flynn 2003 Mol Cell 11:671"},
    "neher2006": {"species": "ecoli", "protease": "clpxp", "weight": 0.90,
                  "kind": "trap", "citation": "Neher 2006 Mol Cell 22:193"},
    "bhat2013": {"species": "caulobacter", "protease": "clpp", "weight": 0.80,
                 "kind": "trap", "citation": "Bhat 2013 Mol Microbiol 88:1083"},
    "lunge2020": {"species": "mtuberculosis", "protease": "clpc1", "weight": 0.70,
                  "kind": "knockdown", "citation": "Lunge 2020 JBC 295:9455"},
    "graham2013": {"species": "saureus", "protease": "clpc", "weight": 0.60,
                   "kind": "trap", "citation": "Graham 2013 J Bacteriol 195:4506"},
    "feng2013": {"species": "saureus", "protease": "clpp", "weight": 0.60,
                 "kind": "trap", "citation": "Feng 2013 J Proteome Res 12:547"},
    "ziemski2021": {"species": "mtuberculosis", "protease": "clpcp", "weight": 0.40,
                    "kind": "interaction", "citation": "Ziemski 2021 FEBS J 288:111"},
}
# Proteases absent from both focal organisms (see CLP_MACHINERY below).
CLPC_LIKE = {"clpc", "clpc1", "clpcp"}
CLPC_ONLY_CAP = 0.45

# The Clp/AAA+ machinery census (docs §3.0, the spec's adaptor-census suggestion). Queried by
# SEQUENCE, not gene symbol: HS11286 annotates only 1,053/5,728 entries with a real symbol and
# clpA/sspB/clpK are all symbol-invisible there. Both focal organisms carry the COMPLETE ClpXP/ClpAP
# system, which is why the spec's "CM1 without SspB contributes zero" gate is inert here (it
# multiplies every protein by 1.0) and is recorded as provenance with weight 0.
CLP_MACHINERY = ("clpX", "clpP", "clpA", "clpB", "clpS", "sspB", "rssB",
                 "lon", "hslU", "hslV", "ftsH", "aat", "smpB", "ssrA")
# Absent from Enterobacteriaceae — every published BacPROTAC is a cyclomarin-A-derived ligand of the
# ClpC1 N-terminal domain (the phosphoarginine degron receptor), a Firmicute/Actinobacteria feature.
CLP_MACHINERY_ABSENT = ("clpC", "mcsB", "mecA")


# --------------------------------------------------------------------------- scoring (10h)
# All weights/thresholds are module-level so the composite is auditable and tunable, exactly as
# src/essentiality.py is consumed by 07h. A sub-score that is entirely absent for a protein is
# DROPPED and the remaining weights renormalised in 10h — never zero-filled.
W_EXPERIMENTAL = 0.45   # measured Clp-substrate / turnover evidence in the organism itself
W_TRANSFER = 0.35       # evidence lifted from an ortholog (E. coli -> Kp, or the xbac trap pool)
W_DEGRON = 0.20         # the sequence+structure degron prior

# The degron prior is deliberately the LOWEST weight despite having the HIGHEST coverage. That
# asymmetry is the direct fix for the legacy composite, which correlated r=0.958 with its own degron
# score and r=0.883 with one (inverted) boolean.

# Within the degron prior: terminal structural exposure dominates, because it is the only dense,
# correctly-signed, full-coverage feature. Motifs contribute only through an exposed terminus.
W_DEGRON_MOTIF = 0.45
W_DEGRON_EXPOSURE = 0.55

TIER_HIGH = 0.55
TIER_MEDIUM = 0.30
# A `high` call needs either a hard evidence source or a confident score: `degradability_confidence`
# (the retained weight mass) must clear this, so a protein can never reach the top tier on the
# degron prior alone.
MIN_CONFIDENCE_FOR_HIGH = 0.55
# 10g ships its ESM-C head into the composite only if the orthogroup-aware AUROC clears this AND
# beats the length/abundance baselines; otherwise the column is emitted with weight 0.
ESMC_MIN_AUROC = 0.65

# Clp accessibility (09a) is a GATE, not a score input: `degradability_score` means "intrinsically
# labile once recruited", accessibility means "reachable by the cytoplasmic machinery at all". They
# are combined multiplicatively only in the shortlist.
MIN_CLP_ACCESSIBILITY = 0.5


def halflife_evidence(halflife_class: str | None, trapped: bool = False) -> float | None:
    """Map a turnover class (+ trap corroboration) to a [0,1] Clp-substrate evidence sub-score.

    Rapid turnover alone is weak, protease-ambiguous evidence: Lon recognises exposed hydrophobic
    patches without an adaptor and accounts for a large share of fast turnover in E. coli
    (Gur & Sauer 2008; the caveat docs §3 raises via Olivares/Sauer). So `fast` corroborated by a
    Clp trap scores near the top, while `fast` alone is capped mid-scale. Unmeasured returns None so
    the weight is renormalised away rather than read as "measured stable".
    """
    c = (halflife_class or "").strip().lower()
    if trapped:
        return 1.0 if c == "fast" else 0.90
    if c == "fast":
        return 0.55
    if c == "intermediate":
        return 0.35
    if c == "stable":
        return 0.0
    return None


def trap_evidence(papers: list[str] | None) -> tuple[float | None, bool]:
    """Pooled, per-paper-weighted trap evidence and a ClpC-only flag.

    Returns (score, clpc_only). `score` is the maximum per-paper weight (evidence does not compound
    — two traps in the same organism are not twice the proof), capped at CLPC_ONLY_CAP when every
    supporting paper used a ClpC-family protease that neither focal organism encodes.
    """
    keys = [p for p in (papers or []) if p in TRAP_PAPERS]
    if not keys:
        return None, False
    clpc_only = all(TRAP_PAPERS[k]["protease"] in CLPC_LIKE for k in keys)
    score = max(TRAP_PAPERS[k]["weight"] for k in keys)
    if clpc_only:
        score = min(score, CLPC_ONLY_CAP)
    return round(float(score), 4), clpc_only


def renormalised_score(parts: dict[str, float | None],
                       weights: dict[str, float]) -> tuple[float | None, float]:
    """Weighted mean over the AVAILABLE parts, plus the retained weight mass (the confidence).

    Same contract as the 07h composite: a part that is None is dropped and the remaining weights are
    renormalised, so a missing track lowers confidence rather than pushing the score toward zero.
    Returns (score, confidence); score is None when nothing is available.
    """
    num = 0.0
    den = 0.0
    for key, w in weights.items():
        v = parts.get(key)
        if v is None or pd.isna(v):
            continue
        num += float(w) * float(v)
        den += float(w)
    if den <= 0:
        return None, 0.0
    total = sum(weights.values())
    return round(num / den, 4), round(den / total, 4)


def degradability_tier(score: float | None, confidence: float,
                       hard_evidence: bool = False) -> str:
    """Evidence-driven tier: high / medium / low / insufficient_evidence.

    `insufficient_evidence` is a first-class state, distinct from `low`. The legacy axis reported all
    4,675 no-ortholog Kp proteins as `low`, indistinguishable in the browser from a protein measured
    to be stable. A `high` call requires a hard evidence source (own or ortholog Clp trap, or fast
    turnover corroborated by a trap) or a score that clears TIER_HIGH *with* enough retained weight
    mass — never the degron prior alone.
    """
    if score is None or confidence <= 0:
        return "insufficient_evidence"
    if hard_evidence or (score >= TIER_HIGH and confidence >= MIN_CONFIDENCE_FOR_HIGH):
        return "high"
    if score >= TIER_MEDIUM:
        return "medium"
    return "low"


if __name__ == "__main__":  # `python src/degradability.py` runs the motif archetype tests
    selftest_motifs()
    print("motif archetype self-tests passed:", ", ".join(MOTIFS))
    for t in (34.1, 199.7, 411.3, 40.0, 20.0):
        print(f"  t1/2={t:>7} min -> k_deg={growth_corrected_kdeg(t)} "
              f"proteolytic t1/2={proteolytic_half_life(t)}")
